const listProduct = [
    {
      id: 1,
      name: 'ลิ้นจี่สด เกรดพรีเมียม',
      price: 12,
      image: '/product/lychee.jpg',
      rating: 5,
      reviews: 738,
      badge: 'HOT',
      badgeColor: 'bg-red-500',
    },
    {
      id: 2,
      name: 'ทุเรียนหมอนทอง คัดสวน',
      price: 70,
      image: '/product/durian.jpg',
      rating: 5,
      reviews: 738,
      badge: 'BEST DEALS',
      badgeColor: 'bg-blue-500',
    },
    {
      id: 3,
      name: 'เงาะโรงเรียน สดใหม่',
      price: 30,
      image: '/product/rambutan.jpg',
      rating: 5,
      reviews: 738,
      badge: '25% OFF',
      badgeColor: 'bg-green-500',
    },
    {
      id: 4,
      name: 'มังคุดคัดเกรด',
      price: 25,
      image: '/product/mangosteen.jpg',
      rating: 5,
      reviews: 738,
      badge: '',
      badgeColor: '',
    },
    {
      id: 5,
      name: 'ลิ้นจี่สด เกรดพรีเมียม',
      price: 12,
      image: '/product/lychee.jpg',
      rating: 5,
      reviews: 738,
      badge: 'HOT',
      badgeColor: 'bg-red-500',
    },
    {
      id: 6,
      name: 'ทุเรียนหมอนทอง คัดสวน',
      price: 70,
      image: '/product/durian.jpg',
      rating: 5,
      reviews: 738,
      badge: 'BEST DEALS',
      badgeColor: 'bg-blue-500',
    },
    {
      id: 7,
      name: 'เงาะโรงเรียน สดใหม่',
      price: 30,
      image: '/product/rambutan.jpg',
      rating: 5,
      reviews: 738,
      badge: '25% OFF',
      badgeColor: 'bg-green-500',
    },
    {
      id: 8,
      name: 'มังคุดคัดเกรด',
      price: 25,
      image: '/product/mangosteen.jpg',
      rating: 5,
      reviews: 738,
      badge: '',
      badgeColor: '',
    },
    {
      id: 9,
      name: 'ลิ้นจี่สด เกรดพรีเมียม',
      price: 12,
      image: '/product/lychee.jpg',
      rating: 5,
      reviews: 738,
      badge: 'HOT',
      badgeColor: 'bg-red-500',
    },
    {
      id: 10,
      name: 'ทุเรียนหมอนทอง คัดสวน',
      price: 70,
      image: '/product/durian.jpg',
      rating: 5,
      reviews: 738,
      badge: 'BEST DEALS',
      badgeColor: 'bg-blue-500',
    },
    {
      id: 11,
      name: 'เงาะโรงเรียน สดใหม่',
      price: 30,
      image: '/product/rambutan.jpg',
      rating: 5,
      reviews: 738,
      badge: '25% OFF',
      badgeColor: 'bg-green-500',
    },
    {
      id: 12,
      name: 'มังคุดคัดเกรด',
      price: 25,
      image: '/product/mangosteen.jpg',
      rating: 5,
      reviews: 738,
      badge: '',
      badgeColor: '',
    },
    {
      id: 13,
      name: 'ลิ้นจี่สด เกรดพรีเมียม',
      price: 12,
      image: '/product/lychee.jpg',
      rating: 5,
      reviews: 738,
      badge: 'HOT',
      badgeColor: 'bg-red-500',
    },
    {
      id: 14,
      name: 'ทุเรียนหมอนทอง คัดสวน',
      price: 70,
      image: '/product/durian.jpg',
      rating: 5,
      reviews: 738,
      badge: 'BEST DEALS',
      badgeColor: 'bg-blue-500',
    },
    {
      id: 15,
      name: 'เงาะโรงเรียน สดใหม่',
      price: 30,
      image: '/product/rambutan.jpg',
      rating: 5,
      reviews: 738,
      badge: '25% OFF',
      badgeColor: 'bg-green-500',
    },
    {
      id: 16,
      name: 'มังคุดคัดเกรด',
      price: 25,
      image: '/product/mangosteen.jpg',
      rating: 5,
      reviews: 738,
      badge: '',
      badgeColor: '',
    },
  ];


  export default listProduct;